### ISSUE TITLE
pano project

### ISSUE THREAD

**Issue by HakunaMatata052** [marcofugaro/three-projected-material#62]
Hello author, I am a beginner at three. js

May I ask how to project the panorama onto the specified model? In fact, currently only one map can be used.

I hope to project a panoramic cube onto the entire model.

**Comment by marcofugaro** [comment]
Hey, what do you mean as "panoramic cube", could you share an example?

**Comment by HakunaMatata052** [comment]
<img width="415" alt="111" src="https://github.com/marcofugaro/three-projected-material/assets/38306114/c1d33e57-edb3-4a46-a678-81e97db43ef2">    

For example, I can project the Panorama onto the whole model, so that I can achieve the effect of moving in space like matterport.

**Comment by marcofugaro** [comment]
What you're trying to do exceeds the scope of this library, you should look into equirectangular projection, an example of projecting it onto a sphere model is here: https://threejs.org/examples/#webgl_panorama_equirectangular

Otherwise check out this discussion about matterport techniques:
https://discourse.threejs.org/t/matterport-features-for-threejs/36891
